import type {
  User,
  Facility,
  Patient,
  ClinicalCase,
  SyncLog,
  AuditEntry,
  Notification,
  ChartDataPoint,
} from '@/types'

export const mockUsers: User[] = [
  {
    id: 'usr-001',
    email: 'jean-pierre.lukusa@medinsight.cd',
    name: 'Dr. Jean-Pierre Lukusa',
    role: 'doctor',
    avatar: '',
    facility: 'fac-001',
    department: 'Cardiologie',
    phone: '+243 81 200 001',
    createdAt: '2024-01-15T08:00:00Z',
    lastLogin: '2026-07-11T09:30:00Z',
    isActive: true,
  },
  {
    id: 'usr-002',
    email: 'patrice.kabongo@medinsight.cd',
    name: 'Dr. Patrice Kabongo',
    role: 'doctor',
    avatar: '',
    facility: 'fac-001',
    department: 'Neurologie',
    phone: '+243 81 200 002',
    createdAt: '2024-02-20T10:00:00Z',
    lastLogin: '2026-07-10T14:15:00Z',
    isActive: true,
  },
  {
    id: 'usr-003',
    email: 'consolee.bakonga@medinsight.cd',
    name: 'Infirmière Consolée Bakonga',
    role: 'nurse',
    avatar: '',
    facility: 'fac-002',
    department: 'Urgences',
    phone: '+243 81 200 003',
    createdAt: '2024-03-10T07:30:00Z',
    lastLogin: '2026-07-11T06:45:00Z',
    isActive: true,
  },
  {
    id: 'usr-004',
    email: 'admin@medinsight.cd',
    name: 'Jean-Pierre Lukusa',
    role: 'admin',
    avatar: '',
    facility: 'fac-001',
    department: 'Administration',
    phone: '+243 81 200 004',
    createdAt: '2023-11-01T09:00:00Z',
    lastLogin: '2026-07-11T11:00:00Z',
    isActive: true,
  },
  {
    id: 'usr-005',
    email: 'esperance.ilunga@medinsight.cd',
    name: 'Dr. Espérance Ilunga',
    role: 'researcher',
    avatar: '',
    facility: 'fac-003',
    department: 'Recherche Clinique',
    phone: '+243 81 200 005',
    createdAt: '2024-04-05T08:45:00Z',
    lastLogin: '2026-07-09T16:20:00Z',
    isActive: true,
  },
  {
    id: 'usr-006',
    email: 'clovis.lukusa@medinsight.cd',
    name: 'Clovis Lukusa',
    role: 'viewer',
    avatar: '',
    facility: 'fac-004',
    department: 'Direction',
    phone: '+243 81 200 006',
    createdAt: '2024-05-12T12:00:00Z',
    lastLogin: '2026-07-08T10:30:00Z',
    isActive: true,
  },
  {
    id: 'usr-007',
    email: 'pierrette.nlandu@medinsight.cd',
    name: 'Infirmière Pierrette Nlandu',
    role: 'nurse',
    avatar: '',
    facility: 'fac-005',
    department: 'Pédiatrie',
    phone: '+243 81 200 007',
    createdAt: '2024-06-18T07:00:00Z',
    lastLogin: '2026-07-11T08:00:00Z',
    isActive: true,
  },
  {
    id: 'usr-008',
    email: 'dieudonne.mutombo@medinsight.cd',
    name: 'Dr. Dieudonné Mutombo',
    role: 'doctor',
    avatar: '',
    facility: 'fac-002',
    department: 'Chirurgie Orthopédique',
    phone: '+243 81 200 008',
    createdAt: '2024-07-22T09:15:00Z',
    lastLogin: '2026-07-11T13:45:00Z',
    isActive: true,
  },
]

export const mockFacilities: Facility[] = [
  {
    id: 'fac-001',
    name: 'Hôpital Général de Kinshasa',
    type: 'hospital',
    address: 'Avenue de l\'Hôpital',
    city: 'Kinshasa',
    phone: '+243 81 222 0001',
    email: 'info@hgr-kinshasa.cd',
    bedCount: 2000,
    departmentCount: 40,
    staffCount: 4500,
    isActive: true,
    createdAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'fac-002',
    name: 'Cliniques Universitaires de Kinshasa',
    type: 'hospital',
    address: 'Boulevard du 30 Juin',
    city: 'Kinshasa',
    phone: '+243 81 222 0002',
    email: 'contact@cukinshasa.cd',
    bedCount: 1200,
    departmentCount: 30,
    staffCount: 3200,
    isActive: true,
    createdAt: '2023-02-15T00:00:00Z',
  },
  {
    id: 'fac-003',
    name: 'Clinique Ngaliema',
    type: 'clinic',
    address: 'Avenue Mombo',
    city: 'Kinshasa',
    phone: '+243 81 222 0003',
    email: 'accueil@cliniquengaliema.cd',
    bedCount: 300,
    departmentCount: 12,
    staffCount: 600,
    isActive: true,
    createdAt: '2023-03-20T00:00:00Z',
  },
  {
    id: 'fac-004',
    name: 'Hôpital du Cinquantenaire',
    type: 'hospital',
    address: 'Avenue du Cinquantenaire',
    city: 'Kinshasa',
    phone: '+243 81 222 0004',
    email: 'administration@hopital-cinquantenaire.cd',
    bedCount: 500,
    departmentCount: 15,
    staffCount: 1100,
    isActive: true,
    createdAt: '2023-04-10T00:00:00Z',
  },
  {
    id: 'fac-005',
    name: 'Hôpital Saint Joseph',
    type: 'hospital',
    address: 'Avenue Sendwe',
    city: 'Kinshasa',
    phone: '+243 81 222 0005',
    email: 'info@hopital-saintjoseph.cd',
    bedCount: 400,
    departmentCount: 14,
    staffCount: 800,
    isActive: true,
    createdAt: '2023-05-05T00:00:00Z',
  },
]

export const mockPatients: Patient[] = [
  {
    id: 'pat-001',
    firstName: 'Félix',
    lastName: 'Tshisekedi',
    dateOfBirth: '1973-03-15',
    gender: 'M',
    phone: '+243 81 301 0001',
    address: 'Avenue de la Paix, Gombe, Kinshasa',
    bloodType: 'A+',
    allergies: ['Pénicilline'],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1001',
    isActive: true,
    createdAt: '2024-01-20T08:00:00Z',
    lastVisit: '2026-06-15T10:30:00Z',
  },
  {
    id: 'pat-002',
    firstName: 'Jeanne',
    lastName: 'Lubaya',
    dateOfBirth: '1991-07-22',
    gender: 'F',
    phone: '+243 81 301 0002',
    address: 'Boulevard du 30 Juin, Lingwala, Kinshasa',
    bloodType: 'O+',
    allergies: [],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1002',
    isActive: true,
    createdAt: '2024-02-14T09:30:00Z',
    lastVisit: '2026-07-01T14:00:00Z',
  },
  {
    id: 'pat-003',
    firstName: 'Aristide',
    lastName: 'Kabila',
    dateOfBirth: '1964-11-08',
    gender: 'M',
    phone: '+243 81 301 0003',
    address: 'Rue de l\'Évangéli, Barumbu, Kinshasa',
    bloodType: 'B-',
    allergies: ['Aspirine', 'Iode'],
    facilityId: 'fac-002',
    medicalRecordNumber: 'MRN-1003',
    isActive: true,
    createdAt: '2024-03-01T07:15:00Z',
    lastVisit: '2026-05-20T11:00:00Z',
  },
  {
    id: 'pat-004',
    firstName: 'Hélène',
    lastName: 'Diangienda',
    dateOfBirth: '1982-01-30',
    gender: 'F',
    phone: '+243 81 301 0004',
    address: 'Avenue Tombalbaye, Kinshasa',
    bloodType: 'AB+',
    allergies: ['Latex'],
    facilityId: 'fac-003',
    medicalRecordNumber: 'MRN-1004',
    isActive: true,
    createdAt: '2024-03-18T10:00:00Z',
    lastVisit: '2026-07-05T09:00:00Z',
  },
  {
    id: 'pat-005',
    firstName: 'Célestin',
    lastName: 'Mobutu',
    dateOfBirth: '1956-05-12',
    gender: 'M',
    phone: '+243 81 301 0005',
    address: 'Boulevard Lumumba, Limete, Kinshasa',
    bloodType: 'O-',
    allergies: [],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1005',
    isActive: true,
    createdAt: '2024-04-05T08:45:00Z',
    lastVisit: '2026-06-28T15:30:00Z',
  },
  {
    id: 'pat-006',
    firstName: 'Béatrice',
    lastName: 'Ngoma',
    dateOfBirth: '1997-09-03',
    gender: 'F',
    phone: '+243 81 301 0006',
    address: 'Avenue Sendwe, Ngaliema, Kinshasa',
    bloodType: 'A-',
    allergies: ['Pollens'],
    facilityId: 'fac-004',
    medicalRecordNumber: 'MRN-1006',
    isActive: true,
    createdAt: '2024-04-22T11:30:00Z',
    lastVisit: '2026-07-08T08:15:00Z',
  },
  {
    id: 'pat-007',
    firstName: 'Sylvain',
    lastName: 'Kasai',
    dateOfBirth: '1970-12-18',
    gender: 'M',
    phone: '+243 81 301 0007',
    address: 'Rue Kasa-Vubu, Kintambo, Kinshasa',
    bloodType: 'B+',
    allergies: ['AINS'],
    facilityId: 'fac-005',
    medicalRecordNumber: 'MRN-1007',
    isActive: true,
    createdAt: '2024-05-10T09:00:00Z',
    lastVisit: '2026-06-10T13:00:00Z',
  },
  {
    id: 'pat-008',
    firstName: 'Cécile',
    lastName: 'Kalonji',
    dateOfBirth: '1985-04-25',
    gender: 'F',
    phone: '+243 81 301 0008',
    address: 'Avenue des Aviateurs, Gombe, Kinshasa',
    bloodType: 'O+',
    allergies: [],
    facilityId: 'fac-002',
    medicalRecordNumber: 'MRN-1008',
    isActive: true,
    createdAt: '2024-05-28T07:30:00Z',
    lastVisit: '2026-07-10T10:45:00Z',
  },
  {
    id: 'pat-009',
    firstName: 'Augustin',
    lastName: 'Lumumba',
    dateOfBirth: '1951-08-07',
    gender: 'M',
    phone: '+243 81 301 0009',
    address: 'Boulevard du 30 Juin, Lingwala, Kinshasa',
    bloodType: 'A+',
    allergies: ['Morphine'],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1009',
    isActive: true,
    createdAt: '2024-06-15T10:15:00Z',
    lastVisit: '2026-06-22T09:30:00Z',
  },
  {
    id: 'pat-010',
    firstName: 'Monique',
    lastName: 'Kasa',
    dateOfBirth: '1979-06-14',
    gender: 'F',
    phone: '+243 81 301 0010',
    address: 'Avenue Mombo, Ngaliema, Kinshasa',
    bloodType: 'AB-',
    allergies: [],
    facilityId: 'fac-003',
    medicalRecordNumber: 'MRN-1010',
    isActive: true,
    createdAt: '2024-07-01T08:00:00Z',
    lastVisit: '2026-07-03T14:15:00Z',
  },
  {
    id: 'pat-011',
    firstName: 'Félix',
    lastName: 'Tshombe',
    dateOfBirth: '1988-02-20',
    gender: 'M',
    phone: '+243 81 301 0011',
    address: 'Rue de Kinshasa, Bandalungwa',
    bloodType: 'O+',
    allergies: ['Crustacés'],
    facilityId: 'fac-004',
    medicalRecordNumber: 'MRN-1011',
    isActive: true,
    createdAt: '2024-07-18T09:45:00Z',
    lastVisit: '2026-06-30T11:30:00Z',
  },
  {
    id: 'pat-012',
    firstName: 'Grâce',
    lastName: 'Nsenda',
    dateOfBirth: '1973-10-11',
    gender: 'F',
    phone: '+243 81 301 0012',
    address: 'Avenue Kasa-Vubu, Kalamu, Kinshasa',
    bloodType: 'B+',
    allergies: [],
    facilityId: 'fac-005',
    medicalRecordNumber: 'MRN-1012',
    isActive: true,
    createdAt: '2024-08-05T07:00:00Z',
    lastVisit: '2026-07-09T16:00:00Z',
  },
  {
    id: 'pat-013',
    firstName: 'Aristide',
    lastName: 'Kalonji',
    dateOfBirth: '1996-01-05',
    gender: 'M',
    phone: '+243 81 301 0013',
    address: 'Boulevard Mangengeng, Masina, Kinshasa',
    bloodType: 'A-',
    allergies: [],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1013',
    isActive: true,
    createdAt: '2024-08-22T11:00:00Z',
    lastVisit: '2026-07-11T08:30:00Z',
  },
  {
    id: 'pat-014',
    firstName: 'Espérance',
    lastName: 'Kabongo',
    dateOfBirth: '1962-07-28',
    gender: 'F',
    phone: '+243 81 301 0014',
    address: 'Avenue de la République, Gombe, Kinshasa',
    bloodType: 'O-',
    allergies: ['Pénicilline', 'Sulfamides'],
    facilityId: 'fac-002',
    medicalRecordNumber: 'MRN-1014',
    isActive: true,
    createdAt: '2024-09-10T08:30:00Z',
    lastVisit: '2026-06-25T10:00:00Z',
  },
  {
    id: 'pat-015',
    firstName: 'Norbert',
    lastName: 'Luyindula',
    dateOfBirth: '1975-03-09',
    gender: 'M',
    phone: '+243 81 301 0015',
    address: 'Rue des Écoles, Ndjili, Kinshasa',
    bloodType: 'AB+',
    allergies: ['Iode', 'Latex'],
    facilityId: 'fac-003',
    medicalRecordNumber: 'MRN-1015',
    isActive: true,
    createdAt: '2024-09-28T09:15:00Z',
    lastVisit: '2026-07-06T13:45:00Z',
  },
]

export const mockClinicalCases: ClinicalCase[] = [
  {
    id: 'cas-001',
    title: 'Paludisme sévère à Plasmodium falciparum',
    description: 'Patient de 52 ans, fièvre élevée depuis 5 jours, parasitémie à 200 000/µL. Hémoglobine 8g/dL.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-002',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Paludisme sévère - P. falciparum',
    symptoms: ['Fièvre 40°C', 'Frissons', 'Sueurs', 'Anémie', 'Splénomégalie'],
    treatment: 'Artesunate IV puis Perfloxine per os, transfusion si Hb <7',
    tags: ['Infectiologie', 'Paludisme', 'Urgence'],
    createdAt: '2026-07-01T08:30:00Z',
    updatedAt: '2026-07-05T14:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-002',
    title: 'Pneumonie bilatérale sévère',
    description: 'Pneumonie bilatérale avec détresse respiratoire nécessitant une hospitalisation en réanimation.',
    status: 'in_review',
    priority: 'critical',
    patientId: 'pat-006',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Pneumonie bilatérale à pneumocoque',
    symptoms: ['Fièvre 39.5°C', 'Toux productive', 'Dyspnée', 'Douleur thoracique', 'SpO2 87%'],
    treatment: 'Antibiothérapie IV (Amoxicilline-acide clavulanique), oxygénothérapie',
    tags: ['Pneumologie', 'Réanimation', 'Infection'],
    createdAt: '2026-06-28T02:15:00Z',
    updatedAt: '2026-07-06T09:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-003',
    title: 'Appendicite aiguë',
    description: 'Appendicite aiguë non compliquée, prise en charge chirurgicale en urgence.',
    status: 'resolved',
    priority: 'high',
    patientId: 'pat-010',
    facilityId: 'fac-003',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Appendicite aiguë',
    symptoms: ['Douleur fosse iliaque droite', 'Nausée', 'Vomissement', 'Fièvre 38.5°C'],
    treatment: 'Appendicectomie cœlioscopique',
    tags: ['Chirurgie Digestive', 'Urgence', 'Cœlioscopie'],
    createdAt: '2026-06-20T16:00:00Z',
    updatedAt: '2026-06-22T10:00:00Z',
    resolvedAt: '2026-06-22T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-004',
    title: 'Diabète de type 2 mal contrôlé',
    description: 'Patient diabétique avec HbA1c à 10.5%, nécessitant un ajustement thérapeutique.',
    status: 'active',
    priority: 'medium',
    patientId: 'pat-009',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Diabète de type 2 déséquilibré',
    symptoms: ['Polyurie', 'Polydipsie', 'Perte de poids', 'Fatigue', 'HbA1c 10.5%'],
    treatment: 'Metformine 1000mg x2, Gliclazide 80mg, insulinothérapie envisagée',
    tags: ['Endocrinologie', 'Chronique', 'Diabète'],
    createdAt: '2026-06-15T11:00:00Z',
    updatedAt: '2026-07-08T15:30:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-005',
    title: 'Infarctus du myocarde antérieur',
    description: 'IDMA avec sus-décalage du segment ST, prise en charge en cathlab en urgence.',
    status: 'in_review',
    priority: 'critical',
    patientId: 'pat-001',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Infarctus aigu du myocarde antérieur avec sus-décalage du ST',
    symptoms: ['Douleur thoracique compressive', 'Sueurs', 'Nausée', 'Irradiation bras gauche', 'Sus-décalage ST V1-V4'],
    treatment: 'Angioplastie primaire avec pose de stent, Double antiagrégation plaquettaire',
    tags: ['Cardiologie', 'Urgence', 'Cathlab'],
    createdAt: '2026-07-10T06:00:00Z',
    updatedAt: '2026-07-10T12:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-006',
    title: 'Asthme bronchique sévère',
    description: 'Exacerbation sévère d\'asthme bronchique avec statut asthmatique.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-005',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Exacerbation sévère d\'asthme bronchique',
    symptoms: ['Dyspnée sévère', 'Sifflements', 'Toux nocturne', 'SpO2 90%', 'Utilisation muscles accessoires'],
    treatment: 'Nébulisation Salbutamol + Ipratropium, Corticothérapie IV, Surveillance SpO2',
    tags: ['Pneumologie', 'Urgence', 'Respiratoire'],
    createdAt: '2026-07-09T22:00:00Z',
    updatedAt: '2026-07-11T08:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-007',
    title: 'AVC ischémique territorial sylvien gauche',
    description: 'Accident vasculaire cérébral ischémique du territoire sylvien gauche avec hémiplégie droite.',
    status: 'active',
    priority: 'critical',
    patientId: 'pat-006',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-002',
    diagnosis: 'AVC ischémique du territoire sylvien gauche',
    symptoms: ['Hémiplégie droite', 'Aphasie', 'Déviation conjuguée', 'NIHSS 17'],
    treatment: 'Thrombolyse IV (alteplase), antiagrégation plaquettaire, kinésithérapie',
    tags: ['Neurologie', 'Urgence', 'AVC'],
    createdAt: '2026-07-08T14:30:00Z',
    updatedAt: '2026-07-11T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-008',
    title: 'Infection urinaire haute',
    description: 'Pyélonéphrite aiguë droite avec fièvre et douleur lombaire.',
    status: 'resolved',
    priority: 'medium',
    patientId: 'pat-003',
    facilityId: 'fac-005',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Pyélonéphrite aiguë droite',
    symptoms: ['Fièvre 39.8°C', 'Douleur lombaire droite', 'Pollakiurie', 'Hématurie'],
    treatment: 'Ciprofloxacine 500mg x2 pendant 14 jours, hydratation',
    tags: ['Urologie', 'Infection', 'Antibiothérapie'],
    createdAt: '2026-06-25T09:00:00Z',
    updatedAt: '2026-07-03T11:00:00Z',
    resolvedAt: '2026-07-03T11:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-009',
    title: 'Traumatisme crânien modéré',
    description: 'Traumatisme crânien après accident de la voie publique, GCS 13, scanner cérébral normal.',
    status: 'in_review',
    priority: 'high',
    patientId: 'pat-008',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Traumatisme crânien modéré sans lésion intracrânienne',
    symptoms: ['Perte de connaissance brève', 'Céphalée', 'Nausée', 'GCS 13'],
    treatment: 'Surveillance neurologique, antalgiques, repos',
    tags: ['Neurologie', 'Traumatisme', 'Surveillance'],
    createdAt: '2026-07-07T20:00:00Z',
    updatedAt: '2026-07-10T08:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-010',
    title: 'Insuffisance cardiaque décompensée',
    description: 'Décompensation d\'insuffisance cardiaque gauche avec œdème pulmonaire.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-012',
    facilityId: 'fac-004',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Insuffisance cardiaque gauche décompensée FC 33%',
    symptoms: ['Dyspnée de décubitus', 'Œdème des membres inférieurs', 'Orthopnée', 'Crackles pulmonaires'],
    treatment: 'Furosémide IV, Nitroglycérine, Spironolactone, Bêtabloquant',
    tags: ['Cardiologie', 'Réanimation', 'Chronique'],
    createdAt: '2026-07-05T18:00:00Z',
    updatedAt: '2026-07-11T07:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-011',
    title: 'Cholangite aiguë',
    description: 'Cholangite aiguë sur lithiase cholédoquienne, triade de Charcot.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-004',
    facilityId: 'fac-003',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Cholangite aiguë sur lithiase biliaire',
    symptoms: ['Fièvre 40°C', 'Ictère', 'Douleur hypochondre droit', 'Frissons'],
    treatment: 'Antibiothérapie IV, CPRE en urgence, cholécystectomie programmée',
    tags: ['Chirurgie Digestive', 'Hépatologie', 'Urgence'],
    createdAt: '2026-07-09T10:00:00Z',
    updatedAt: '2026-07-11T09:30:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-012',
    title: 'Grossesse extra-utérine',
    description: 'Grossesse extra-utérine rompue avec hématopéritoine, prise en charge chirurgicale urgente.',
    status: 'resolved',
    priority: 'critical',
    patientId: 'pat-015',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Grossesse extra-utérine tubaire rompue',
    symptoms: ['Douleur pelvienne aiguë', 'Métrorragies', 'Syncope', 'Pâleur', 'Aménorrhée 8 semaines'],
    treatment: 'Salpingectomie urgente par coelioscopie, transfusion sanguine',
    tags: ['Gynécologie', 'Urgence', 'Chirurgie'],
    createdAt: '2026-06-18T03:00:00Z',
    updatedAt: '2026-06-18T08:00:00Z',
    resolvedAt: '2026-06-18T08:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-013',
    title: 'Insuffisance rénale chronique stade 4',
    description: 'Dégradation de la fonction rénale avec DFG à 20 ml/min, préparation à la dialyse.',
    status: 'active',
    priority: 'medium',
    patientId: 'pat-014',
    facilityId: 'fac-005',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Insuffisance rénale chronique stade 4',
    symptoms: ['Œdème', 'Fatigue', 'Anorexie', 'DFG 20 ml/min', 'Créatinine 5.0 mg/dl'],
    treatment: 'Régime hyposodé, EPO, fer, préparation fistule artério-veineuse',
    tags: ['Néphrologie', 'Chronique', 'Dialyse'],
    createdAt: '2026-05-10T14:00:00Z',
    updatedAt: '2026-07-05T11:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-014',
    title: 'Polytraumatisme routier',
    description: 'Polytraumatisme après accident de voiture: fracture du bassin, pneumothorax, hépatoplasie.',
    status: 'in_review',
    priority: 'critical',
    patientId: 'pat-011',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Polytraumatisme: fracture bassin, pneumothorax droit, plaie hépatique grade II',
    symptoms: ['Hémorragie', 'Détresse respiratoire', 'Instabilité hémodynamique', 'Douleur pelvienne'],
    treatment: 'Drain thoracique, embolisation hépatique, ostéosynthèse du bassin',
    tags: ['Traumatologie', 'Réanimation', 'Chirurgie'],
    createdAt: '2026-07-11T01:00:00Z',
    updatedAt: '2026-07-11T12:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-015',
    title: 'Crise hypertensive',
    description: 'Crise hypertensive sévère avec ATCD d\'HTA non traitée, pression 225/135 mmHg.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-009',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Crise hypertensive sévère',
    symptoms: ['PA 225/135 mmHg', 'Céphalée occipitale', 'Troubles visuels', 'Nausée'],
    treatment: 'Nicardipine IV, Catapressan per os, surveillance PA continue',
    tags: ['Cardiologie', 'Urgence', 'Hypertension'],
    createdAt: '2026-07-10T15:00:00Z',
    updatedAt: '2026-07-11T10:30:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-016',
    title: 'Dépression majeure récurrente',
    description: 'Épisode dépressif majeur récidivant avec idées noires, échec du 2ème traitement antidépresseur.',
    status: 'draft',
    priority: 'medium',
    patientId: 'pat-007',
    facilityId: 'fac-005',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Trouble dépressif majeur récurrente sévérité sévère',
    symptoms: ['Tristesse permanente', 'Insomnie', 'Anorexie', 'Idées noires', 'Apathie'],
    treatment: 'Escitalopram 20mg, TCC envisagées, évaluation du risque suicidaire',
    tags: ['Psychiatrie', 'Chronique', 'Suivi'],
    createdAt: '2026-07-08T10:00:00Z',
    updatedAt: '2026-07-08T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-017',
    title: 'Cancer du sein gauche stade IIB',
    description: 'Carcinome canalaire infiltrant du sein gauche, T2N1M0, prise en charge en oncologie.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-013',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-005',
    diagnosis: 'Carcinome canalaire infiltrant du sein gauche T2N1M0',
    symptoms: ['Masse palpable 3cm', 'Adénopathie axillaire', 'Rétraction cutanée'],
    treatment: 'Chimiothérapie néoadjuvante (FEC), chirurgie mastectomie, radiothérapie',
    tags: ['Oncologie', 'Chimiothérapie', 'Suivi'],
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-07-09T14:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-018',
    title: 'Lithiase rénale symptomatique',
    description: 'Calcoli rénaux multiples du rein droit avec colique néphrétique.',
    status: 'resolved',
    priority: 'medium',
    patientId: 'pat-005',
    facilityId: 'fac-003',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Lithiase rénale bilatérale symptomatique',
    symptoms: ['Colique néphrétique', 'Hématurie', 'Nausée', 'Douleur lombaire'],
    treatment: 'Litotritie extracorporelle, drainage urétéral, régime hydrique',
    tags: ['Urologie', 'Chirurgie', 'Lithiase'],
    createdAt: '2026-06-22T21:00:00Z',
    updatedAt: '2026-07-02T10:00:00Z',
    resolvedAt: '2026-07-02T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-019',
    title: 'Intoxication médicamenteuse',
    description: 'Ingestion volontaire de Benzodiazépines, prise en charge en toxicologie.',
    status: 'draft',
    priority: 'high',
    patientId: 'pat-011',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Intoxication aiguë par Benzodiazépines',
    symptoms: ['Somnolence', 'Désorientation', 'Hypotension', 'Dépression respiratoire'],
    treatment: 'Flumazénil, surveillance continue, support psychiatrique',
    tags: ['Toxicologie', 'Urgence', 'Psychiatrie'],
    createdAt: '2026-07-11T04:00:00Z',
    updatedAt: '2026-07-11T04:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-020',
    title: 'Rhumatisme inflammatoire',
    description: 'Poussée de rhumatisme psoriasique avec atteinte des articulations interphalangiennes.',
    status: 'archived',
    priority: 'low',
    patientId: 'pat-004',
    facilityId: 'fac-004',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Rhumatisme psoriasique - poussée articulaire',
    symptoms: ['Douleur articulaire', 'Raideur matinale', 'Gonflement doigts', 'Dactylite'],
    treatment: 'Méthotrexate 15mg/semaine, AINS, corticoïdes locaux',
    tags: ['Rhumatologie', 'Chronique', 'Auto-immun'],
    createdAt: '2025-11-15T09:00:00Z',
    updatedAt: '2026-03-20T11:00:00Z',
    resolvedAt: '2026-03-20T11:00:00Z',
    attachments: [],
    notes: [],
  },
]

export const mockSyncLogs: SyncLog[] = [
  {
    id: 'sync-001',
    entityType: 'ClinicalCase',
    entityId: 'cas-001',
    action: 'create',
    status: 'synced',
    timestamp: '2026-07-01T08:30:00Z',
  },
  {
    id: 'sync-002',
    entityType: 'ClinicalCase',
    entityId: 'cas-002',
    action: 'create',
    status: 'synced',
    timestamp: '2026-06-28T02:15:00Z',
  },
  {
    id: 'sync-003',
    entityType: 'ClinicalCase',
    entityId: 'cas-005',
    action: 'update',
    status: 'pending',
    timestamp: '2026-07-10T12:00:00Z',
  },
  {
    id: 'sync-004',
    entityType: 'Patient',
    entityId: 'pat-013',
    action: 'update',
    status: 'synced',
    timestamp: '2026-07-11T08:30:00Z',
  },
  {
    id: 'sync-005',
    entityType: 'ClinicalCase',
    entityId: 'cas-014',
    action: 'create',
    status: 'failed',
    timestamp: '2026-07-11T01:05:00Z',
    errorMessage: 'Erreur de connexion au serveur de synchronisation',
  },
  {
    id: 'sync-006',
    entityType: 'AuditEntry',
    entityId: 'aud-001',
    action: 'create',
    status: 'synced',
    timestamp: '2026-07-11T09:30:00Z',
  },
  {
    id: 'sync-007',
    entityType: 'ClinicalCase',
    entityId: 'cas-007',
    action: 'update',
    status: 'pending',
    timestamp: '2026-07-11T10:00:00Z',
  },
  {
    id: 'sync-008',
    entityType: 'Patient',
    entityId: 'pat-008',
    action: 'create',
    status: 'synced',
    timestamp: '2026-07-10T10:45:00Z',
  },
  {
    id: 'sync-009',
    entityType: 'ClinicalCase',
    entityId: 'cas-015',
    action: 'update',
    status: 'failed',
    timestamp: '2026-07-11T10:35:00Z',
    errorMessage: 'Conflit de version détecté',
  },
  {
    id: 'sync-010',
    entityType: 'ClinicalCase',
    entityId: 'cas-004',
    action: 'update',
    status: 'synced',
    timestamp: '2026-07-08T15:30:00Z',
  },
]

export const mockAuditEntries: AuditEntry[] = [
  {
    id: 'aud-001',
    userId: 'usr-001',
    action: 'Consultation dossier',
    entity: 'Patient',
    entityId: 'pat-001',
    details: 'Consultation du dossier médical de Félix Tshisekedi',
    ipAddress: '192.168.1.10',
    timestamp: '2026-07-11T09:30:00Z',
  },
  {
    id: 'aud-002',
    userId: 'usr-001',
    action: 'Modification traitement',
    entity: 'ClinicalCase',
    entityId: 'cas-004',
    details: 'Ajout de Gliclazide 80mg au protocole de traitement du Diabète de type 2',
    ipAddress: '192.168.1.10',
    timestamp: '2026-07-08T15:30:00Z',
  },
  {
    id: 'aud-003',
    userId: 'usr-008',
    action: 'Création cas clinique',
    entity: 'ClinicalCase',
    entityId: 'cas-001',
    details: 'Création du cas clinique "Paludisme sévère"',
    ipAddress: '192.168.1.22',
    timestamp: '2026-07-01T08:30:00Z',
  },
  {
    id: 'aud-004',
    userId: 'usr-004',
    action: 'Accès aux statistiques',
    entity: 'Dashboard',
    entityId: 'dashboard-001',
    details: 'Consultation du tableau de bord administrateur',
    ipAddress: '192.168.1.5',
    timestamp: '2026-07-11T11:00:00Z',
  },
  {
    id: 'aud-005',
    userId: 'usr-002',
    action: 'Ajout note clinique',
    entity: 'ClinicalCase',
    entityId: 'cas-007',
    details: 'Ajout d\'une note de suivi neurologique pour le cas AVC',
    ipAddress: '192.168.1.15',
    timestamp: '2026-07-10T08:00:00Z',
  },
  {
    id: 'aud-006',
    userId: 'usr-003',
    action: 'Consultation dossier',
    entity: 'Patient',
    entityId: 'pat-006',
    details: 'Consultation du dossier médical de Béatrice Ngoma',
    ipAddress: '192.168.1.30',
    timestamp: '2026-07-08T08:15:00Z',
  },
  {
    id: 'aud-007',
    userId: 'usr-001',
    action: 'Changement de statut',
    entity: 'ClinicalCase',
    entityId: 'cas-003',
    details: 'Statut modifié de "active" à "resolved" - Appendicite aiguë',
    ipAddress: '192.168.1.10',
    timestamp: '2026-06-22T10:00:00Z',
  },
  {
    id: 'aud-008',
    userId: 'usr-005',
    action: 'Export de données',
    entity: 'ClinicalCase',
    entityId: 'cas-017',
    details: 'Export du rapport du cas Cancer du sein en PDF',
    ipAddress: '192.168.1.40',
    timestamp: '2026-07-09T14:00:00Z',
  },
  {
    id: 'aud-009',
    userId: 'usr-004',
    action: 'Modification paramètres',
    entity: 'Facility',
    entityId: 'fac-001',
    details: 'Mise à jour des informations de l\'Hôpital Général de Kinshasa',
    ipAddress: '192.168.1.5',
    timestamp: '2026-07-05T09:00:00Z',
  },
  {
    id: 'aud-010',
    userId: 'usr-008',
    action: 'Ajout pièce jointe',
    entity: 'ClinicalCase',
    entityId: 'cas-001',
    details: 'Ajout du scanner en pièce jointe',
    ipAddress: '192.168.1.22',
    timestamp: '2026-07-02T14:30:00Z',
  },
  {
    id: 'aud-011',
    userId: 'usr-001',
    action: 'Consultation dossier',
    entity: 'Patient',
    entityId: 'pat-009',
    details: 'Consultation du dossier médical d\'Augustin Lumumba',
    ipAddress: '192.168.1.10',
    timestamp: '2026-07-11T09:45:00Z',
  },
  {
    id: 'aud-012',
    userId: 'usr-007',
    action: 'Modification traitement',
    entity: 'ClinicalCase',
    entityId: 'cas-010',
    details: 'Ajustement de la posologie de Furosémide pour le cas Insuffisance cardiaque',
    ipAddress: '192.168.1.35',
    timestamp: '2026-07-11T07:15:00Z',
  },
  {
    id: 'aud-013',
    userId: 'usr-006',
    action: 'Connexion',
    entity: 'User',
    entityId: 'usr-006',
    details: 'Connexion à la plateforme MedInsight',
    ipAddress: '192.168.1.50',
    timestamp: '2026-07-08T10:30:00Z',
  },
  {
    id: 'aud-014',
    userId: 'usr-002',
    action: 'Création cas clinique',
    entity: 'ClinicalCase',
    entityId: 'cas-016',
    details: 'Création du cas clinique "Dépression majeure récurrente"',
    ipAddress: '192.168.1.15',
    timestamp: '2026-07-08T10:00:00Z',
  },
  {
    id: 'aud-015',
    userId: 'usr-004',
    action: 'Gestion utilisateur',
    entity: 'User',
    entityId: 'usr-008',
    details: 'Activation du compte de Dr. Dieudonné Mutombo',
    ipAddress: '192.168.1.5',
    timestamp: '2026-07-07T14:00:00Z',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'Nouveau cas clinique assigné',
    message: 'Le cas "Paludisme sévère" vous a été assigné.',
    type: 'info',
    read: false,
    createdAt: '2026-07-11T08:30:00Z',
    link: '/cases/cas-001',
  },
  {
    id: 'notif-002',
    title: 'Synchronisation échouée',
    message: 'La synchronisation du cas "Polytraumatisme routier" a échoué. Veuillez réessayer.',
    type: 'error',
    read: false,
    createdAt: '2026-07-11T01:05:00Z',
    link: '/sync',
  },
  {
    id: 'notif-003',
    title: 'Cas résolu',
    message: 'Le cas "Appendicite aiguë" a été marqué comme résolu.',
    type: 'success',
    read: true,
    createdAt: '2026-06-22T10:00:00Z',
    link: '/cases/cas-003',
  },
  {
    id: 'notif-004',
    title: 'Rappel de suivi',
    message: 'Le patient Jeanne Lubaya a un rendez-vous de suivi demain à 14h00.',
    type: 'warning',
    read: false,
    createdAt: '2026-07-11T09:00:00Z',
  },
  {
    id: 'notif-005',
    title: 'Mise à jour système',
    message: 'MedInsight sera mis à jour ce soir entre 22h et 23h.',
    type: 'info',
    read: true,
    createdAt: '2026-07-10T16:00:00Z',
  },
  {
    id: 'notif-006',
    title: 'Patient critique',
    message: 'Le patient Béatrice Ngoma nécessite une attention immédiate (AVC ischémique).',
    type: 'error',
    read: false,
    createdAt: '2026-07-08T14:30:00Z',
    link: '/cases/cas-007',
  },
  {
    id: 'notif-007',
    title: 'Document prêt',
    message: 'Le rapport d\'analyse du cas "Cancer du sein" est prêt au téléchargement.',
    type: 'success',
    read: true,
    createdAt: '2026-07-09T14:30:00Z',
    link: '/cases/cas-017',
  },
  {
    id: 'notif-008',
    title: 'Connexion suspecte',
    message: 'Une connexion inhabituelle a été détectée sur votre compte depuis une adresse IP inconnue.',
    type: 'warning',
    read: false,
    createdAt: '2026-07-11T03:00:00Z',
  },
  {
    id: 'notif-009',
    title: 'Cas en attente de validation',
    message: '3 cas cliniques sont en attente de votre validation.',
    type: 'info',
    read: false,
    createdAt: '2026-07-11T07:00:00Z',
    link: '/cases?status=in_review',
  },
  {
    id: 'notif-010',
    title: 'Erreur de synchronisation',
    message: 'Conflit de version détecté pour le cas "Crise hypertensive". Résolution manuelle requise.',
    type: 'error',
    read: true,
    createdAt: '2026-07-11T10:35:00Z',
    link: '/sync',
  },
]

export const mockChartData = {
  casesByMonth: [
    { name: 'Jan', value: 18 },
    { name: 'Fév', value: 22 },
    { name: 'Mar', value: 15 },
    { name: 'Avr', value: 28 },
    { name: 'Mai', value: 32 },
    { name: 'Juin', value: 25 },
    { name: 'Juil', value: 35 },
    { name: 'Août', value: 12 },
    { name: 'Sep', value: 20 },
    { name: 'Oct', value: 27 },
    { name: 'Nov', value: 30 },
    { name: 'Déc', value: 16 },
  ] satisfies ChartDataPoint[],

  casesByStatus: [
    { name: 'Brouillon', value: 3 },
    { name: 'Actif', value: 8 },
    { name: 'En revue', value: 4 },
    { name: 'Résolu', value: 3 },
    { name: 'Archivé', value: 2 },
  ] satisfies ChartDataPoint[],

  casesByFacility: [
    { name: 'Hôpital Général de Kinshasa', value: 8 },
    { name: 'Cliniques Universitaires de Kinshasa', value: 5 },
    { name: 'Clinique Ngaliema', value: 4 },
    { name: 'Hôpital du Cinquantenaire', value: 2 },
    { name: 'Hôpital Saint Joseph', value: 3 },
  ] satisfies ChartDataPoint[],

  treatmentOutcomes: [
    { name: 'Succès', value: 12 },
    { name: 'Échec', value: 2 },
    { name: 'En cours', value: 5 },
  ] satisfies ChartDataPoint[],
}

export const mockSyncQueue = mockSyncLogs

export const mockTreatments: ClinicalCase[] = mockClinicalCases.filter(
  (c) => c.treatment
)

export const mockStudies: ClinicalCase[] = mockClinicalCases.filter(
  (c) => c.status === 'resolved'
)
