export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CREATE_FAILED: 'RESOURCE_CREATE_FAILED',
  RESOURCE_UPDATE_FAILED: 'RESOURCE_UPDATE_FAILED',
  RESOURCE_DELETE_FAILED: 'RESOURCE_DELETE_FAILED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  CONFLICT: 'CONFLICT',
  SERVER_ERROR: 'SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  DATABASE_ERROR: 'DATABASE_ERROR',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
} as const

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode]

export interface ApiErrorResponse {
  success: false
  message: string
  code: ErrorCodeType
  errors: Record<string, string>
}
